#############################################################################
# Makefile for building: 3d_graphics.app/Contents/MacOS/3d_graphics
# Generated by qmake (3.1) (Qt 5.15.16)
# Project:  3d_graphics.pro
# Template: app
# Command: /opt/homebrew/bin/qmake -o Makefile 3d_graphics.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers -Iobj -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang -F/opt/homebrew/Cellar/qt@5/5.15.16_2/lib
QMAKE         = /opt/homebrew/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/homebrew/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/homebrew/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 3d_graphics1.0.0
DISTDIR = /Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics/obj/3d_graphics1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks
LIBS          = $(SUBLIBS) -F/opt/homebrew/Cellar/qt@5/5.15.16_2/lib -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = main.cpp \
		src/shapeViewer.cpp \
		src/camera.cpp \
		src/transformation.cpp obj/moc_shapeViewer.cpp
OBJECTS       = obj/main.o \
		obj/shapeViewer.o \
		obj/camera.o \
		obj/transformation.o \
		obj/moc_shapeViewer.o
DIST          = /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/lex.prf \
		3d_graphics.pro include/shapeViewer.h \
		include/remap.h \
		include/transformation.h \
		include/camera.h main.cpp \
		src/shapeViewer.cpp \
		src/camera.cpp \
		src/transformation.cpp
QMAKE_TARGET  = 3d_graphics
DESTDIR       = 
TARGET        = 3d_graphics.app/Contents/MacOS/3d_graphics

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT__QMAKE_STASH_ = /Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics/.qmake.stash
EXPORT_VALID_ARCHS = arm64
EXPORT_DEFAULT_ARCHS = arm64
EXPORT_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(if $(ARCHS), $(ARCHS), $(if $(EXPORT_DEFAULT_ARCHS), $(EXPORT_DEFAULT_ARCHS), $(EXPORT_VALID_ARCHS))))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ARCHS), $(EXPORT_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics/3d_graphics.pro


include /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

3d_graphics.app/Contents/MacOS/3d_graphics:  $(OBJECTS)  
	@test -d 3d_graphics.app/Contents/MacOS/ || mkdir -p 3d_graphics.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 3d_graphics.pro /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang/qmake.conf /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qdevice.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/device_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/unix.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/macx.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/sanitize.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang-mac.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qconfig.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bodymovin_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang/qmake.conf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exclusive_builds.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/sdk.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/toolchain.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_pre.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resolve_config.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_post.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/objective_c.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/mac.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/warn_on.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources_functions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/moc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/opengl.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/uic.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/thread.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qmake_use.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/file_copies.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/rez.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/asset_catalogs.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/testcase_targets.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exceptions.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/yacc.prf \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/lex.prf \
		3d_graphics.pro \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile 3d_graphics.pro
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qdevice.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/device_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/unix.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/macx.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/sanitize.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/gcc-base-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/common/clang-mac.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/qconfig.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bodymovin_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_charts_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_core_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designer_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_gui_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_help_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_location_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_network_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdf_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3d_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3drender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quick_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_script_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_sql_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_svg_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_webview_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xml_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang/qmake.conf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exclusive_builds.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/sdk.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/toolchain.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_pre.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resolve_config.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/default_post.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/objective_c.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/mac.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/warn_on.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qt.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources_functions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/resources.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/moc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/opengl.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/uic.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/unix/thread.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/qmake_use.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/file_copies.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/rez.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/mac/asset_catalogs.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/testcase_targets.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/exceptions.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/yacc.prf:
/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/lex.prf:
3d_graphics.pro:
/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Resources/QtGui.prl:
/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 3d_graphics.pro

qmake_all: FORCE

3d_graphics.app/Contents/PkgInfo: 
	@test -d 3d_graphics.app/Contents || mkdir -p 3d_graphics.app/Contents
	@$(DEL_FILE) 3d_graphics.app/Contents/PkgInfo
	@echo "APPL????" > 3d_graphics.app/Contents/PkgInfo
3d_graphics.app/Contents/Resources/empty.lproj: 
	@test -d 3d_graphics.app/Contents/Resources || mkdir -p 3d_graphics.app/Contents/Resources
	@touch 3d_graphics.app/Contents/Resources/empty.lproj
	
3d_graphics.app/Contents/Info.plist: 
	@test -d 3d_graphics.app/Contents || mkdir -p 3d_graphics.app/Contents
	@$(DEL_FILE) 3d_graphics.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,io.iosapp.3d-graphics,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},io.iosapp.3d-graphics,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,3d_graphics,g" -e "s,@LIBRARY@,3d_graphics,g" -e "s,\$${EXECUTABLE_NAME},3d_graphics,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang/Info.plist.app >3d_graphics.app/Contents/Info.plist

all: Makefile \
		3d_graphics.app/Contents/PkgInfo \
		3d_graphics.app/Contents/Resources/empty.lproj \
		3d_graphics.app/Contents/Info.plist 3d_graphics.app/Contents/MacOS/3d_graphics

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/shapeViewer.h include/remap.h include/transformation.h include/camera.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp src/shapeViewer.cpp src/camera.cpp src/transformation.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r 3d_graphics.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: obj/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) obj/moc_predefs.h
obj/moc_predefs.h: /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -O2 -std=gnu++1z $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o obj/moc_predefs.h /opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: obj/moc_shapeViewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) obj/moc_shapeViewer.cpp
obj/moc_shapeViewer.cpp: include/shapeViewer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QPointF \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector3D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector3d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector4D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector4d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector2D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector2d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qtimer.h \
		include/camera.h \
		obj/moc_predefs.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/bin/moc
	/opt/homebrew/Cellar/qt@5/5.15.16_2/bin/moc $(DEFINES) --include /Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics/obj/moc_predefs.h -I/opt/homebrew/Cellar/qt@5/5.15.16_2/mkspecs/macx-clang -I/Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics -I/Users/mateuszosik/repos/Uni/Semester6/CG/3d_graphics/include -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers -I/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/17/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/homebrew/Cellar/qt@5/5.15.16_2/lib include/shapeViewer.h -o obj/moc_shapeViewer.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/main.o: main.cpp /opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QApplication \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QMainWindow \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QVBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qboxlayout.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QHBoxLayout \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QSpinBox \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qspinbox.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QLabel \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qlabel.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QPushButton \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qpushbutton.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QFileDialog \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qfiledialog.h \
		include/shapeViewer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QPointF \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector3D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector3d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector4D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector4d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector2D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector2d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qtimer.h \
		include/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/shapeViewer.o: src/shapeViewer.cpp include/shapeViewer.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/QWidget \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtWidgets.framework/Headers/qwidget.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QPointF \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qpoint.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector3D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector3d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector4D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector4d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector2D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector2d.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QTimer \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qtimer.h \
		include/camera.h \
		include/remap.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QImage \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qimage.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QColor \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qcolor.h \
		include/transformation.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QMatrix4x4 \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QPainter \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qpainter.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QMouseEvent \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qevent.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/QRandomGenerator \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtCore.framework/Headers/qrandom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/shapeViewer.o src/shapeViewer.cpp

obj/camera.o: src/camera.cpp include/camera.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector3D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector3d.h \
		include/transformation.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QMatrix4x4 \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qmatrix4x4.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/camera.o src/camera.cpp

obj/transformation.o: src/transformation.cpp include/transformation.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QMatrix4x4 \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qmatrix4x4.h \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/QVector3D \
		/opt/homebrew/Cellar/qt@5/5.15.16_2/lib/QtGui.framework/Headers/qvector3d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/transformation.o src/transformation.cpp

obj/moc_shapeViewer.o: obj/moc_shapeViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_shapeViewer.o obj/moc_shapeViewer.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/3d_graphics/bin || mkdir -p $(INSTALL_ROOT)/opt/3d_graphics/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/3d_graphics/bin/3d_graphics.app
	
	$(QINSTALL) 3d_graphics.app $(INSTALL_ROOT)/opt/3d_graphics/bin/3d_graphics.app
	-$(STRIP) $(INSTALL_ROOT)/opt/3d_graphics/bin/3d_graphics.app/Contents/MacOS/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/3d_graphics/bin/3d_graphics.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/3d_graphics/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

